[package]
name = "signalbox-bot"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "bot"
path = "src/lib.rs"

[dependencies]
signalbox-protocol = { path = "../protocol" }
futures-util.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "io-util", "time", "macros"] }
tokio-tungstenite.workspace = true

[dev-dependencies]
signalbox-core = { path = "../core" }
signalbox-game = { path = "../game" }
ts2-import = { path = "../ts2-import" }
serde_json.workspace = true
