[package]
name = "signalbox-game"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "game"
path = "src/lib.rs"

[dependencies]
signalbox-core = { path = "../core" }
signalbox-protocol = { path = "../protocol" }
rusqlite.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
ts2-import = { path = "../ts2-import" }
